### ISSUE TITLE
demonstrative jupyter notebooks

### ISSUE THREAD

**Issue by evanbiederstedt** [christacaggiano/celfie#1]
Congratulations on the manuscript: https://www.biorxiv.org/content/10.1101/2020.01.15.907022v1"""

I think this is a really interesting concept. 

It looks like you plan to put notebooks here at some point: https://github.com/christacaggiano/celfie/tree/master/jupyter_notebooks

Please update this issue when you do, as it would be great to see. 

Best, Evan Biederstedt

**Comment by christacaggiano** [comment]
Well if you're still interested in it (more than a year later lol) you can kindly find sample code and a demonstrative jupyter notebook at demo.ipynb. Thanks!

**Comment by evanbiederstedt** [comment]
Thanks for this!
