### ISSUE TITLE
celfie returns negative fractions

### ISSUE THREAD

**Issue by GMFranceschini** [christacaggiano/celfie#5]
Dear Christa,
Thank you for developing celfie.
I am trying to apply the analysis to a very controlled dilution experiment we conducted, but I was puzzled to observe that celfie returned often negative fractions in the cell type estimation. Also, different runs lead to very different results (numerical instability?). Is this behaviour expected?  I checked the input files and they seem to be fine.

I am deconvolving 20 samples simultaneously using 3 known pure components + 1 unknown, and other much simpler tools based on quadratic programming or regression on beta seem to easily capture the correct fractions up to few % of error.

Best

**Comment by christacaggiano** [comment]
Hi, CelFiE shouldn't return negative results if the input data was properly formatted, as far as my experience has gone. But I'm happy to help diagnose the problem more if you email me - christa@g.ucla.edu.
