### ISSUE TITLE
A code error in tim.sh 

### ISSUE THREAD

**Issue by xihuimeijing** [christacaggiano/celfie#8]
Hi Christa,

Thank you for developing CelFiE. 

When I use the tim.sh to generate my own TIMs, I found the tim_summed.txt output file was not for regions but for CpG sites. After debugging, I found there is a code error in this line "awk -v window="$window_size" '{print $1 "\t" $2-$window "\t" $3+$window}' $output_file"_sites" > $output_file"_"$window_size". It should be no $ before window inside awk.

Hope this is helpful.

**Comment by christacaggiano** [comment]
Thank you so much for catching that bug!!

**Comment by christacaggiano** [comment]
It is fixed now!
